# Generated by Django 6.0.3 on 2026-04-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='blog/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_blog', models.CharField(choices=[('Политика', 'Политика'), ('Спорт', 'Спорт'), ('Путешевствие', 'Путешевствие')], default='Путешевствие', max_length=100)),
            ],
        ),
    ]
