# Generated by Django 6.0.3 on 2026-04-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
        migrations.AddField(
            model_name='blog',
            name='email_author',
            field=models.EmailField(default='@gmail.com', max_length=254, null=True, verbose_name='введите email автора'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100, verbose_name='введите название блога'),
        ),
    ]
