# Generated by Django 6.0.3 on 2026-04-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='video_url',
        ),
    ]
