# Generated by Django 6.0.3 on 2026-04-07 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('person', models.CharField(default='Ivanov Ivan', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StateNumberCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer_car', models.CharField(default='0_KG_', max_length=10)),
                ('car_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='connection_database.car')),
            ],
        ),
    ]
