# Generated by Django 6.0.3 on 2026-04-07 11:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField()),
                ('choice_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='connection_database.car')),
            ],
        ),
    ]
