# Generated by Django 6.0.3 on 2026-04-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_database', '0003_categorycar_car_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='connection_database.categorycar'),
        ),
    ]
